source 'https://rubygems.org'
gem 'github-pages'
gem 'github-markdown'
gem 'github-linguist'
gem 'escape_utils'
gem 'email_reply_parser'
gem 'sanitize'
gem 'rinku'
gem 'jekyll'
#gem 'activesupport', '~> 4.1.11'
#gem 'yajl-ruby', '~> 1.2.0'
#gem "pygments.rb", '~> 0.6.0'
